services:
  db:
    image: postgres:latest
    user: 1000:1000
    environment:
      POSTGRES_PASSWORD: PostgresPwd
      POSTGRES_USER: pubadmin
      POSTGRES_DB: pubserver
    ports:
      - "54321:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  storage:
    image: minio/minio:RELEASE.2024-10-29T16-01-48Z.fips
    volumes:
      - ./docker-data/data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: MinioPwd
    command: server /data --console-address ":9001"

  atlas:
    image: arigaio/atlas:0.28.1
    container_name: pubserver_migrator
    depends_on:
      - db
    volumes:
      - ./migrations:/migrations
      - ./atlas.hcl:/atlas.hcl
    command: migrate apply --url "postgres://pubadmin:PostgresPwd@db:5432/pubserver?sslmode=disable"

  app:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - db
    container_name: pubserver
    environment:
      APP_CODE: PUBSERVER
      DB_CONNECTION: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: pubserver
      DB_USERNAME: pubadmin
      DB_PASSWORD: PostgresPwd
      DB_LOGGING: false
      # optional, if use this format, DB_HOST, DB_PORT, DB_DATABASE, DB_USERNAME, DB_PASSWORD will be ignored
      # DATABASE_URL: postgres://pubadmin:PostgresPwd@db:5432/pubserver?sslmode=disable
      DB_AUTOMIGRATION: false

      APP_HOST: "0.0.0.0"
      PORT: 4000
      JWT_SECRET: thisisveryrandomsecretstringthatyoushouldnottypemanuallylikethis
      JWT_TOKEN_LIFETIME: 10
      JWT_REFRESH_LIFETIME: 1440
      # OTLP_URL: http://localhost:4318/v1/traces

      S3_REGION: asd
      S3_ENDPOINT: http://storage:9000/
      S3_BUCKET: asd
      S3_KEY_ID: 7hus2R7zlhUM7tleVPgS
      S3_ACCESS_KEY: NxgtLgbi5X2yk6mlpQCz9tKLzqdIEvciFoDnFLiL
      # if "true", will use path style, for compatibility mode such as minIO. example: https://yourendpoint/yourbucket/blablabla
      S3_PUBLIC_ENDPOINT: http://localhost:9000/
      # s3 public endpoint used for presign, if not specified, will use S3_ENDPOINT
      S3_USE_PATH_STYLE: true

      # to enable presign, value must be "true"
      S3_ENABLE_PRESIGN: true
      # presign time in minute
      S3_PRESIGN_TIME: 15

      # SMTP Setting
      SMTP_HOST: sandbox.smtp.mailtrap.io
      SMTP_PORT: 2525
      SMTP_FROM_EMAIL: "no-reply@m8zn.work"
      SMTP_FROM_NAME: "No Reply"
      SMTP_USERNAME:
      SMTP_PASSWORD:

      # OTP Expiry Time in minutes
      OTP_EXPIRED_MINUTE: 5
